### ISSUE TITLE
npm package does not work?

### ISSUE THREAD

**Issue by pierznj** [librehat/sdapi#1]
Hi there - thanks for writing this - means I don't have to! However, when I  install it using `npm install librehat/sdapi`, the resulting import does not work - inspecting the package shows the lib folder is not present. I can use it with git clone and then embedding it, but obviously I'd prefer just to specify it as a dependency. Is this a bug or did I misunderstand something?

**Comment by librehat** [comment]
I'll check! Might be a bad publication

**Comment by librehat** [comment]
It should work, I just tested it in https://npm.runkit.com/sdapi (now published 0.2.2 which has the dependencies bumped to fix the security issues)
